const state = () => ({
  patientId: '',
  patientName: '',
  reportDate: '',
  age: '',
  gender: '',
  interpretation: '',
  EASI: 0,
  BSA: 0,
  IGA: 0,
  'Chest & Shoulder': {
    id: '1',
    'Chest-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Chest-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Shoulder-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Shoulder-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
  },
  'Biceps & Triceps': {
    id: '2',
    'Triceps-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Triceps-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Biceps-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Biceps-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
  },
  'Abs & Backside': {
    id: '3',
    'Backside-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Backside-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Abs-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Abs-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
  },
  'Buttocks & Leg': {
    id: '4',
    'Leg-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Leg-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Buttocks-I': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
    'Buttocks-II': {
      weight: 0,
      reps: 0,
      sets: 0,
      movement: '',
      complete: false,
    },
  },
});

export default state;
